name: build

on:
  push:
    branches: ["C-build"]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4.1.0
    - name: Build Scripts
      run: |
        npm run dev:docker:x86_64
        npm run build:wasm:all
    - name: Archive action artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Upload dist
        path: |
          dist/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        file_glob: true
        tag: "C-dist"
        overwrite: true
